#!/bin/sh
# ~/.xinitrc
# # Executed by startx (run your window manager from here)

xset -b &
/usr/bin/urxvtd -q -f -o &
compton -b -d :0 &

[[ -f ~/.Xresources  ]] && xrdb -merge -I$HOME ~/.Xresources
