# colorscheme
set colorscheme default

# preview images
set draw_borders false
set preview_images true
set preview_images_method w3m

# move to trash
map DD shell mv %s $HOME/.Trash

# new tab in current folder
map <c-n>  eval fm.tab_new('%d')
